/* Generated by tools/build-solutions.js. */
window.BlueBoxSolutions = [
  {
    "fingerprint": "######/#    #/# # .#/#    #/#    #/######[[1,3],[[2,3]]]",
    "solution": "RRDRU"
  },
  {
    "fingerprint": "#######/#  . ##/# .#  #/##    #/#    ##/#     #/#######[[5,3],[[4,2],[4,3]]]",
    "solution": "LDLLUUURRDDLRUULLDDRDDRULULUURRDRDLDDLLUUULURDDDRRULDLU"
  },
  {
    "fingerprint": "########/#  #   #/#    # #/# #    #/#   # .#/##    .#/#    #.#/########[[3,2],[[3,3],[2,4],[2,5]]]",
    "solution": "DDUULLDDRLUURRRDRDDLDLLURRRUULLDUULLDDRDRUUDLLUURRDRRRUULLDLDRRLLDDRLUURRDRDULULUURRDDLLLDDRR"
  },
  {
    "fingerprint": "########/# #.   #/#  .   #/# # #. #/#  #  .#/#      #/#   #  #/########[[2,5],[[2,2],[4,2],[5,4],[3,5]]]",
    "solution": "RRRDRUUULUURDLDDRDLUUUULLDRURRDDLURULLRDDDDRUDLLLDLLUUUURRRLLLDDDRRRURRDDLULLLULUURRRURRDDUULLDLLLDDRDRRRUDLLLULUURRRURRDLL"
  },
  {
    "fingerprint": "########/#.   .##/# .##  #/#   o  #/#|   ###/#      #/# # #  #/########[[6,3],[[5,2],[5,3],[4,4]]]",
    "solution": "LLLLUURRRDRDLUULLLDLDUURRRRDDLLDLURDDRULULLUURRRRDDLDLLUULURRRLLDDDRRULDLUDDLUUU"
  },
  {
    "fingerprint": "########/#      #/#.~*   #/#  .# ##/#      #/#      #/# # #  #/########[[5,3],[[5,4],[2,5],[4,5]]]",
    "solution": "DRDDLUUUDLLUUURRRDLLLDDDRULLLDRRURRRDDLUUUDLLUUURRRDLLLDDDRURRDDLUUUDLLUUURRRDLLULLDURRRDDDLLLLUR"
  },
  {
    "fingerprint": "########/###  # #/#    ~ #/#   #*.#/##   ~ #/#   .~ #/##     #/########[[6,2],[[2,2],[5,2],[2,5]]]",
    "solution": "LLULDDLLURDDRDRRUUULULDDDRDDLLUURUULLDRURDLDRRDRUURDLLLLDRRDRUURUULLULDDDLDRDRRRUU"
  },
  {
    "fingerprint": "########/#  #~~~#/#  #   #/#     ##/# #. # #/#  ~ o.#/# .|   #/########[[6,2],[[2,2],[5,2],[2,3]]]",
    "solution": "LULDDDLDLLUURRLLUURDLDRLDDRRURUDLDRDRRULLUURUULDDDLDRDLLLUUURRDRURUULDDDULLLDDRDRRUDLLULUURRDDRDRRULLLUURDLDRDRRULLDLURUULLLDDRRRR"
  },
  {
    "fingerprint": "########/##   # #/#   o~.#/#   #* #/##~|~~ #/#   .~##/##    ##/########[[4,5],[[2,2],[5,2],[2,5]]]",
    "solution": "URURULDDLLULLURURDDDRDDLLUURUULLDRURDLDDDRRUURUULULLDDDDRRLLUURDULUURDLDDDRDRRUDLLURDRUURUULRDDLLLLUURDURLDDLDR"
  },
  {
    "fingerprint": "########/#   ~~~#/#  #   #/#     ##/#~# ~#~#/#* ~ o.#/#~.|   #/########[[1,2],[[2,2],[5,2],[2,3]]]",
    "solution": "URRRRRDLULDULLLDDRLUURRRDDUULLLDDRRDDRDRRULLULULLUURDLDRUURRDDUULLDDRDDRULULUURRDDLLLDDRDRRUULDRDRRULLULULUURRDDDLDLRRRDLL"
  },
  {
    "fingerprint": "########/###  # #/#    ~ #/# | #*.#/##  o~~#/## . ~ #/##     #/########[[4,5],[[2,2],[5,2],[2,5]]]",
    "solution": "URURULLULDDDRDDLLURDRULUULLURDRDDRRUUULULDDURRDDDLLLUDRRRUUULLDDUULLDRDRRRUULLDURRDDDDLLLUURRDRUURDLLLLDRRDRUURUULLULDDDRRDDRU"
  },
  {
    "fingerprint": "########/# #  # #/#    ~ #/# ~~#*.#/##~~ ~|#/# ~o.~ #/##.  ###/########[[3,6],[[2,2],[3,2],[2,5],[4,4]]]",
    "solution": "URRUUULULDDDLDRUUURRDDLLULLURDRDDDRURULRUULULDRRDDDLLLUULURRLDDRRLLUURDDRDRRUUULLULDRRRDDDLUURULLULDLDDRLDRURLDDRURUDLLURLLUURDDRDRURUULLULDDLDRRRDRULLLLDR"
  }
];
